openapi: 3.0.3
info:
  title: Swagger MyFinBox
  description: |-
    MyFinBox REST API
  version: 1.0.0
tags:
  - name: accounts
    description: Everything about your Accounts
paths:
components:
  schemas:
    #  Request Objects
    AccountCreateResource:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the account (read-only).
        firstName:
          type: string
          example: Jon
          description: The first name of the account holder.
        lastName:
          type: string
          example: Doe
          description: The last name of the account holder.
        emailAddress:
          type: string
          example: jondoe@email.com
          description: >
            The email address of the account holder. It must be unique and follow the format specified in RFC 5322.

    ExpenseResource:
      type: object
      properties:
        expenseId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the expense (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the expense.
        categoryId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the category associated with the expense for provided account ID.
        paymentType:
          type: string
          example: Cash
          description: The payment method used for the expense (Cash or Card).
        amount:
          type: number
          example: 30.50
          description: The amount of the expense.
        currencyCode:
          type: string
          example: MDL
          pattern: '^[A-Z]{3}$'
          description: The ISO 4217 currency code in uppercase (e.g., USD, EUR).
        expenseDate:
          type: string
          format: date
          example: 2023-04-01
          description: The date of the expense in ISO 8601 format (YYYY-MM-DD).
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the expense was created (read-only).
        description:
          type: string
          example: Course buying
          description: Additional description attached to the expense.

    ExpenseCategoryResource:
      type: object
      properties:
        categoryId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the expense category (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the expense category.
        name:
          type: string
          example: Fun
          description: The name of the category.
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the expense category was created (read-only).

    IncomeSourceResource:
      type: object
      properties:
        incomeSourceId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the income source (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the income source.
        name:
          type: string
          example: Business
          description: The name of the income source.
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the income source was created (read-only).
