openapi: 3.0.3
info:
  title: Swagger MyFinBox
  description: |-
    MyFinBox REST API
  version: 1.0.0
tags:
  - name: accounts
    description: Operations related to accounts
  - name: expenses
    description: Operations related to incomes and income sources
  - name: incomes
    description: Operations related to incomes and income sources
  - name: plans
    description: Operations related to spending plans

servers:
  - url: https://myfinbox.io/api/v1

paths:
components:
  schemas:
    #  Request Objects
    AccountResource:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the account (read-only).
        firstName:
          type: string
          example: Jon
          description: The first name of the account holder.
        lastName:
          type: string
          example: Doe
          description: The last name of the account holder.
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the expense was created (read-only).
        zoneId:
          type: string
          example: Europe/Paris
          description: The user's time zone taken from browser, default 'Europe/Chisinau'
        currency:
          type: string
          example: USD
          description: The user's currency taken from locale, default MDL
          readOnly: true
        emailAddress:
          type: string
          example: jondoe@email.com
          description: >
            The email address of the account holder. It must be unique and follow the format specified in RFC 5322.

    ExpenseResource:
      type: object
      properties:
        expenseId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the expense (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the expense.
        categoryId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the category associated with the expense for provided account ID.
        paymentType:
          type: string
          example: Cash
          description: The payment method used for the expense (Cash or Card).
        amount:
          type: number
          example: 30.50
          description: The amount of the expense.
        currencyCode:
          type: string
          example: MDL
          pattern: '^[A-Z]{3}$'
          description: The ISO 4217 currency code in uppercase (e.g., USD, EUR).
        expenseDate:
          type: string
          format: date
          example: 2023-04-01
          description: The date of the expense in ISO 8601 format (YYYY-MM-DD).
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the expense was created (read-only).
        description:
          type: string
          example: Course buying
          description: Additional description attached to the expense.

    ExpenseCategoryResource:
      type: object
      properties:
        categoryId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the expense category (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the expense category.
        name:
          type: string
          example: Fun
          description: The name of the category.
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the expense category was created (read-only).

    IncomeSourceResource:
      type: object
      properties:
        incomeSourceId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the income source (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the income source.
        name:
          type: string
          example: Business
          description: The name of the income source.
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the income source was created (read-only).

    IncomeResource:
      type: object
      properties:
        incomeId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the income (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the income.
        incomeSourceId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the income source associated with the income for provided account ID.
        paymentType:
          type: string
          example: Cash
          description: The payment method used for the expense (Cash or Card).
        amount:
          type: number
          example: 30.50
          description: The amount of the income.
        currencyCode:
          type: string
          example: MDL
          pattern: '^[A-Z]{3}$'
          description: The ISO 4217 currency code in uppercase (e.g., USD, EUR).
        incomeDate:
          type: string
          format: date
          example: 2023-04-01
          description: The date of the income in ISO 8601 format (YYYY-MM-DD).
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the income was created (read-only).
        description:
          type: string
          example: Base salary
          description: Additional description attached to the income.

    PlanResource:
      type: object
      properties:
        planId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the spending plan (read-only).
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the spending plan.
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the spending plan was created (read-only).
        name:
          type: string
          example: My monthly plan
          description: The name of the spending plan.
        amount:
          type: number
          example: 1000
          description: The amount of the spending plan.
        currencyCode:
          type: string
          example: MDL
          pattern: '^[A-Z]{3}$'
          description: The ISO 4217 currency code in uppercase (e.g., USD, EUR).
        description:
          type: string
          example: My base plan for tracking all spending
          description: Additional description attached to the spending plan.

    CreateJarResource:
      type: object
      properties:
        jarId:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the jar (read-only).
        creationTimestamp:
          type: string
          readOnly: true
          example: 2024-03-23T10:00:04.224870Z
          description: The timestamp when the jar was created (read-only).
        amountToReach:
          type: number
          example: 550
          readOnly: true
          description: The calculated amount to reach from jar percentage and spending plan amount.
        currencyCode:
          type: string
          example: MDL
          readOnly: true
          pattern: '^[A-Z]{3}$'
          description: The ISO 4217 currency code in uppercase (e.g., USD, EUR), taken from plan.
        name:
          type: string
          example: Necessities
          description: The name of the jar.
        percentage:
          type: integer
          example: 55
          description: The jar percentage a value, accepted [1-100].
        description:
          type: string
          example: "Necessities spending: Rent, Food, Bills etc."
          description: Additional description attached to the jar.

    JarCategoryModificationResource:
      type: object
      description: Object representing the modification of expense categories associated with a jar for tracking expenses.
      properties:
        categories:
          type: array
          items:
            type: object
            properties:
              categoryId:
                type: string
                format: uuid
                description: Unique identifier for the expense category.
              toAdd:
                type: boolean
                default: true
                example: true
                description: Flag indicating whether to add or remove the category.

    CreateClassicPlanResource:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
          example: 3b257779-a5db-4e87-9365-72c6f8d4977d
          description: The ID of the account that submitted the spending plan.
        amount:
          type: number
          example: 1000
          description: The amount of the spending plan.
        currencyCode:
          type: string
          example: MDL
          pattern: '^[A-Z]{3}$'
          description: The ISO 4217 currency code in uppercase (e.g., USD, EUR).
