# This workflows will build a Java project with Maven, and cache/restore any dependencies to improve the workflows execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflows uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Server CI

on:
  push:
    branches: [ "main" ]
    paths: [ 'server/**', '.github/workflows/server-ci.yml' ]
  pull_request:
    branches: [ "main" ]
    paths: [ 'server/**', '.github/workflows/server-ci.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Test and Build 'server' with maven
        run: ./server/mvnw --batch-mode --update-snapshots  clean verify -f server/pom.xml
