# This workflows will build a Java project with Maven, and cache/restore any dependencies to improve the workflows execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflows uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Server CI

on:
  push:
    branches: [ "main" ]
    paths: [ 'server/**', '.github/workflows/server-ci.yml' ]
  pull_request:
    branches: [ "main" ]
    paths: [ 'server/**', '.github/workflows/server-ci.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Test and Build 'server' with maven
        run: ${{ github.workspace }}/server/mvnw --batch-mode --update-snapshots  clean verify -f ${{ github.workspace }}/server/pom.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Reports
          path: ${{ github.workspace }}/server/target/failsafe-reports/*Spec.xml
          reporter: java-junit
          fail-on-error: true

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/server/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 70
